[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.1"
axum = "0.6.1"
hyper = { version = "0.14.23", features = ["full"] }
hyper-rustls = "0.23.2"
once_cell = "1.16.0"
serde_json = "1.0.89"
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread"] }
tower-livereload = "0.7.0"
web-push-native = { path = "../web_push" }
