[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.4"
base64ct = { version = "1.5.3", features = ["alloc", "std"] }
hyper = { version = "0.14.23", features = ["full"] }
hyper-rustls = "0.23.2"
once_cell = "1.17.0"
serde_json = "1.0.91"
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread"] }
tower-livereload = "0.7.2"
web-push-native = { path = "../web_push" }
