[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.12"
base64ct = { version = "1.6.0", features = ["alloc", "std"] }
hyper = { version = "0.14.25", features = ["full"] }
hyper-rustls = "0.24.0"
once_cell = "1.17.1"
serde_json = "1.0.95"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
tower-livereload = "0.7.3"
web-push-native = { path = "../web_push" }
