[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.10"
base64ct = { version = "1.6.0", features = ["alloc", "std"] }
hyper = { version = "0.14.25", features = ["full"] }
hyper-rustls = "0.23.2"
once_cell = "1.17.1"
serde_json = "1.0.94"
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
tower-livereload = "0.7.3"
web-push-native = { path = "../web_push" }
