[package]
authors = ["Leo Gaskin <leo.gaskin@le0.gs>"]
categories = ["cryptography", "network-programming", "web-programming"]
description = "Generic Event Delivery Using Http Push (web-push) components implemented according to RFC8030"
edition = "2021"
homepage = "https://github.com/leotaku/web-push-native"
keywords = ["webpush", "web-push", "http-push", "rust-crypto"]
license = "MIT OR Apache-2.0"
name = "web-push-native"
readme = "README.md"
repository = "https://github.com/leotaku/web-push-native"
version = "0.1.2"

[lib]
doctest = true

[features]
default = ["serialization", "vapid"]
serialization = ["serde", "base64ct"]
vapid = ["jwt-simple", "base64ct"]

[dependencies]
aes-gcm = "0.10.1"
base64ct = { version = "1.5.3", features = ["alloc", "std"], optional = true }
ece-native = { version = "0.1.2", path = "../ece" }
hkdf = "0.12.3"
http = "0.2.8"
jwt-simple = { version = "0.11.2", optional = true }
p256 = { version = "0.11.1", features = ["ecdh"] }
serde = { version = "1.0.150", features = ["derive"], optional = true }
sha2 = "0.10.6"

[dev-dependencies]
once_cell = "1.16.0"
