[package]
edition = "2021"
name = "web-push-native"
readme = "README.md"
version = "0.1.0-pre"

[dependencies]
aes-gcm = "0.10.1"
base64 = "0.13.0"
ece-native = { version = "0.1.0-pre", path = "../ece" }
hkdf = "0.12.3"
http = "0.2.8"
jwt-simple = { version = "0.11.1" }
p256 = { version = "0.11.1", features = ["ecdh"] }
sha2 = "0.10.2"

[dev-dependencies]
once_cell = "1.14.0"
