[package]
authors = ["Leo Gaskin <leo.gaskin@le0.gs>"]
categories = ["cryptography", "network-programming", "web-programming"]
description = "Generic Event Delivery Using Http Push (web-push) components implemented according to RFC8030"
edition = "2021"
homepage = "https://github.com/leotaku/web-push-native"
keywords = ["webpush", "web-push", "http-push", "rust-crypto"]
license = "MIT OR Apache-2.0"
name = "web-push-native"
readme = "README.md"
repository = "https://github.com/leotaku/web-push-native"
version = "0.1.0-pre2"

[lib]
doctest = false

[dependencies]
aes-gcm = "0.10.1"
base64 = "0.13.1"
ece-native = { version = "0.1.0-pre3", path = "../ece" }
hkdf = "0.12.3"
http = "0.2.8"
jwt-simple = "0.11.1"
p256 = { version = "0.11.1", features = ["ecdh"] }
sha2 = "0.10.6"

[dev-dependencies]
once_cell = "1.15.0"
