[package]
authors = ["Leo Gaskin <leo.gaskin@le0.gs>"]
categories = ["cryptography", "network-programming", "web-programming"]
description = "Generic Event Delivery Using Http Push (web-push) components implemented according to RFC8030"
edition = "2021"
homepage = "https://github.com/leotaku/web-push-native"
keywords = ["webpush", "web-push", "http-push", "rust-crypto"]
license = "MIT OR Apache-2.0"
name = "web-push-native"
readme = "README.md"
repository = "https://github.com/leotaku/web-push-native"
version = "0.1.0-pre4"

[lib]
doctest = true

[features]
default = ["serde", "vapid"]
serde = ["dep:serde", "dep:base64"]
vapid = ["dep:jwt-simple", "dep:base64"]

[dependencies]
aes-gcm = "0.10.1"
base64 = { version = "0.13.1", optional = true }
ece-native = { version = "0.1.0-pre4", path = "../ece" }
hkdf = "0.12.3"
http = "0.2.8"
jwt-simple = { version = "0.11.1", optional = true }
p256 = { version = "0.11.1", features = ["ecdh"] }
serde = { version = "1.0.147", optional = true }
sha2 = "0.10.6"

[dev-dependencies]
once_cell = "1.15.0"
